version: "3"

services:
  s3:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ARCH: arm64
        #ARCH: x86_64
    image: whomobile/mount-s3:latest
    env_file:
      - .env
    # command: /start.sh
    # command: mount-s3 s3bucket /mnt/s3 && tail -f /dev/null
    # command: tail -f /dev/null
    volumes:
      - ./local:/mnt/local
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
